issuer: http://dex.auth.svc.cluster.local:5556/dex
storage:
  type: kubernetes
  config:
    inCluster: true
web:
  http: 0.0.0.0:5556
logger:
  level: "debug"
  format: text
oauth2:
  skipApprovalScreen: true
enablePasswordDB: true

staticPasswords:
- email: admin@kubeflow.com
  hash: $2b$10$7rlrsR0svw3ON0A7gLVVRuXFXz890XfrP8vRSeGywI7YlqnJni.3e
  username: admin
  userID: 08a8684b-db88-4b73-90a9-3cd1661f5466
- email: app1@kubeflow.com
  hash: $2b$10$7rlrsR0svw3ON0A7gLVVRuXFXz890XfrP8vRSeGywI7YlqnJni.3e
  username: app1
  userID: 08a8684b-db88-4c72-90a1-3cd1661f5477


staticClients:
- id: kubeflow-oidc-authservice
  redirectURIs: ["/login/oidc"]
  name: 'Dex Login Application'
  secret: pUBnBOY80SnXgjibTYM9ZWNzY2xreNGQok
